# Generated by Django 6.0.3 on 2026-04-13 08:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amnt', models.FloatField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(35000)], verbose_name='Сумма кредита ($)')),
                ('loan_term', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Срок кредита (месяцев)')),
                ('loan_int_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5.42), django.core.validators.MaxValueValidator(23.22)], verbose_name='Процентная ставка (%)')),
                ('loan_intent', models.CharField(blank=True, choices=[('PERSONAL', 'Личные нужды'), ('EDUCATION', 'Образование'), ('MEDICAL', 'Медицина'), ('VENTURE', 'Бизнес'), ('HOMEIMPROVEMENT', 'Ремонт'), ('DEBTCONSOLIDATION', 'Рефинансирование')], max_length=50, null=True, verbose_name='Цель кредита')),
                ('loan_grade', models.CharField(blank=True, choices=[('A', 'A - высокая'), ('B', 'B - хорошая'), ('C', 'C - удовлетворительная'), ('D', 'D - повышенный риск'), ('E', 'E - высокий риск'), ('F', 'F - значительный риск'), ('G', 'G - наивысший риск')], max_length=1, null=True, verbose_name='Рейтинг')),
                ('probability_default', models.FloatField(blank=True, null=True, verbose_name='Вероятность дефолта')),
                ('decision', models.CharField(blank=True, choices=[('APPROVE', 'Одобрено'), ('REJECT', 'Отказано')], max_length=10, null=True, verbose_name='Решение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кредитная заявка',
                'verbose_name_plural': 'Кредитные заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
