# Generated by Django 6.0.3 on 2026-04-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='cb_person_default_on_file',
            field=models.CharField(blank=True, choices=[('Y', 'Да'), ('N', 'Нет')], max_length=1, null=True, verbose_name='Просрочки по кредитам'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='loan_percent_income',
            field=models.FloatField(blank=True, null=True, verbose_name='Отношение кредита к доходу'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='person_emp_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Стаж работы (лет)'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='person_home_ownership',
            field=models.CharField(blank=True, choices=[('RENT', 'Аренда'), ('OWN', 'Собственность'), ('MORTGAGE', 'Ипотека'), ('OTHER', 'Другое')], max_length=20, null=True, verbose_name='Тип жилья'),
        ),
        migrations.AddField(
            model_name='creditapplication',
            name='person_income',
            field=models.FloatField(blank=True, null=True, verbose_name='Годовой доход'),
        ),
    ]
