# Generated by Django 6.0.3 on 2026-04-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0002_creditapplication_cb_person_default_on_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplication',
            name='loan_grade',
        ),
    ]
