# Generated by Django 6.0.3 on 2026-04-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0003_remove_creditapplication_loan_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditapplication',
            name='loan_term',
        ),
    ]
