# Generated by Django 6.0.4 on 2026-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_score', '0004_remove_creditapplication_loan_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditapplication',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
