# Generated by Django 6.0.3 on 2026-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit_score',
            field=models.IntegerField(blank=True, help_text='От 300 до 850', null=True, verbose_name='Кредитный рейтинг'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_default_history',
            field=models.BooleanField(default=False, help_text='Были ли просрочки/дефолты по кредитам', verbose_name='Были ли дефолты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_ownership',
            field=models.CharField(choices=[('RENT', 'Аренда'), ('OWN', 'Собственность'), ('MORTGAGE', 'Ипотека'), ('OTHER', 'Другое')], default='RENT', max_length=20, verbose_name='Тип жилья'),
        ),
    ]
